version: '3'
services:
  web:
    build:
      context: .
      args:
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432
        - POSTGRES_DB=sampleapp
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - DJANGO_SETTINGS_MODULE=sampleapp.settings
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: bash -c "dockerize -wait tcp://db:5432 -timeout 20s && ./manage.py migrate && ./manage.py loaddata data.json && gunicorn sampleapp.wsgi -b 0.0.0.0:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=sampleapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=sampleapp.settings
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sampleapp
